{
 "title": "Consensus BFT",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "channel",
    "query": {
     "query": "label_values({job=~\".*orderer.*\"}, channel)"
    }
   },
   {
    "name": "instance",
    "query": {
     "query": "label_values({job=~\".*orderer.*\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "View",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "consensus_bft_view_number{instance=~\"$instance\",channel=~\"$channel\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Leader ID",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "consensus_bft_view_leader_id{instance=~\"$instance\",channel=~\"$channel\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Phase",
     "type": "stat",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 4 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "consensus_bft_view_phase{instance=~\"$instance\",channel=~\"$channel\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Latency Batch Processing",
     "type": "timeseries",
     "description": "latency for processing of the batches. From the moment a node receives a prepare until it makes a delivery (before commit). How much time is needed to process the batches and exchange messages. It is decomposed by time (done rate), if it grows, it is probably not very good, but there are no exact criteria yet.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "targets": [
      {
       "expr": "rate(consensus_bft_view_latency_batch_processing_sum{instance=~\"$instance\",channel=~\"$channel\"}[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Latency Batch Save",
     "type": "timeseries",
     "description": "When the consensus has made a decision, they send it to the factory for saving and the factory does something with it, saves it and returns it back.The call to save a block in the storage is a delay.If it increases, it's also an very bad.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "targets": [
      {
       "expr": "rate(consensus_bft_view_latency_batch_save_sum{instance=~\"$instance\",channel=~\"$channel\"}[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Proposal sequence",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
     "targets": [
      {
       "expr": "rate(consensus_bft_view_proposal_sequence{instance=~\"$instance\",channel=~\"$channel\"}[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Decisions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "targets": [
      {
       "expr": "rate(consensus_bft_view_decisions{instance=~\"$instance\",channel=~\"$channel\"}[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Count TXs all",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "rate(consensus_bft_view_count_txs_all{instance=~\"$instance\",channel=~\"$channel\"}[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Count TXs in batch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "targets": [
      {
       "expr": "rate(consensus_bft_view_count_txs_in_batch{instance=~\"$instance\",channel=~\"$channel\"}[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Size Batch",
     "type": "timeseries",
     "description": "When the consensus has made a decision, they send it to the factory for saving and the factory does something with it, saves it and returns it back.The call to save a block in the storage is a delay.If it increases, it's also an disaster.",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "rate(consensus_bft_view_size_batch{instance=~\"$instance\",channel=~\"$channel\"}[$__interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pool Count",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pool count of elements",
     "type": "timeseries",
     "description": "the number of elements in the consensus pool, gauge, it is necessary to show exactly how many there are with history (-1 - looks like a joint), if something is broken - it is accumulated and clogged up to some limit (the size of all requests by bytes, the size of how many fit here and some other), if it grows - it's not good",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "consensus_bft_pool_count_of_elements{instance=~\"$instance\",channel=~\"$channel\"}",
       "legendFormat": "{{ channel }} {{ instance }}"
      }
     ]
    },
    {
     "title": "Pool count of elements all and latency",
     "type": "timeseries",
     "description": "number of elements in the requesters pool, same as consensus_bft_pool_count_of_elements, only counter. To be aware of short jumps. Spread out over time. \n\n\n/consensus_bft_pool_latency_of_elements - delay time of finding the requesters in the pool. It counts the time when we put it into the pool and when we remove it from the pool. Histogram. You can decompose it by time and see the growth of latency. If it starts to grow, it is not very good. We need some limits. It would be good to put long-term growth in the yellow level, but we don't have any criteria yet. We need to race it somewhere and see how it is displayed on the chart and how it behaves.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "rate(consensus_bft_pool_count_of_elements_all{instance=~\"$instance\",channel=~\"$channel\"}[$__interval])",
       "legendFormat": "{{ instance }}"
      },
      {
       "expr": "rate(consensus_bft_pool_latency_of_elements_sum{instance=~\"$instance\",channel=~\"$channel\"}[$__interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Fail Add Request",
     "type": "timeseries",
     "description": "when we can't add reqs to the pool it grows. If it grows, it is very (🔴) bad. Two reasons - the size is bigger or the semaphore is full. Counter, we need to decompose by time, on one chart we need to fit three charts - reason one, reason two, their sum. The reason is on line 7.",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "rate(consensus_bft_pool_count_of_fail_add_request{instance=~\"$instance\",channel=~\"$channel\"}[$__interval])",
       "legendFormat": "{{ reason }} {{ instance }}"
      },
      {
       "expr": "sum(rate(consensus_bft_pool_count_of_fail_add_request{instance=~\"$instance\",channel=~\"$channel\"}[$__interval])) by (instance)",
       "legendFormat": "total {{ instance }}"
      }
     ]
    },
    {
     "title": "Leader Forward Request",
     "type": "timeseries",
     "description": "if after selecting a leader, the accumulated requests have not been processed, then these requests are forwarded to the leader. It's not a terrible thing.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(consensus_bft_pool_count_leader_forward_request{instance=~\"$instance\",channel=~\"$channel\"}[$__interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Timeout Two Step",
     "type": "timeseries",
     "description": "practicing a second timeout when the leader is not behaving adequately and we start a leader re-election. If this happens frequently, it is a yellow danger level.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(consensus_bft_pool_count_timeout_two_step{instance=~\"$instance\",channel=~\"$channel\"}[$__interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Delete Request",
     "type": "timeseries",
     "description": "if nothing happened during the second timeout, then unprocessed messages from the requests pool can be deleted (in violation of the BFT algorithm), the counter is expanded by time, in general it should always be 0, if positive - it is a red danger level.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "rate(consensus_bft_pool_count_of_delete_request{instance=~\"$instance\",channel=~\"$channel\"}[$__interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Reconfig",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "targets": [
      {
       "expr": "rate(consensus_bft_consensus_reconfig{instance=~\"$instance\",channel=~\"$channel\"}[$__interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Latency Sync",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "targets": [
      {
       "expr": "rate(consensus_bft_consensus_latency_sync_sum{instance=~\"$instance\",channel=~\"$channel\"}[$__interval])",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "View Change",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Current",
     "type": "timeseries",
     "description": "it's like view_number, only for view change structure, to make a transition between views you need a lot of things and in this transition for a year and a half was found an error, when in the intermediate state nodes hung, and for this purpose was introduced real view number, when we view number increased, but remains in the old view, this is the real view number. So far this thing is for developers.",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "consensus_bft_viewchange_current_view{instance=~\"$instance\",channel=~\"$channel\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Real",
     "type": "timeseries",
     "description": "it's like view_number, only for view change structure, to make a transition between views you need a lot of things and in this transition for a year and a half was found an error, when in the intermediate state nodes hung, and for this purpose was introduced real view number, when we view number increased, but remains in the old view, this is the real view number. So far this thing is for developers.",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 4 },
     "targets": [
      {
       "expr": "consensus_bft_viewchange_real_view{instance=~\"$instance\",channel=~\"$channel\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Next",
     "type": "timeseries",
     "description": "it's like view_number, only for view change structure, to make a transition between views you need a lot of things and in this transition for a year and a half was found an error, when in the intermediate state nodes hung, and for this purpose was introduced real view number, when we view number increased, but remains in the old view, this is the real view number. So far this thing is for developers.",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 4 },
     "targets": [
      {
       "expr": "consensus_bft_viewchange_next_view{instance=~\"$instance\",channel=~\"$channel\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "WAL",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count of Files",
     "type": "timeseries",
     "description": "write ahead log, it works and runs separately. There is one parameter here - it is the number of files. At one time it was discovered that files and their sizes grow infinitely, and because of that disk space was bad. To detect such problems now there is such a parameter. It should be 1-2, if it starts to grow more (5-6) - it is a yellow level, if for 10 and more - it is red. Can clog the disk and it will end there.",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "Files" } },
     "targets": [
      {
       "expr": "consensus_bft_wal_count_of_files{instance=~\"$instance\",channel=~\"$channel\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Blacklist",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Count",
     "type": "timeseries",
     "description": "Now it is not, but there is a possibility to set up a consensus, (now the leader, until he discredits himself, he processes everything, there is a vulnerability attack on the leader), to prevent this thing from happening you can say that this particular leader should calculate a certain number of solutions and pass the leadership on. For this purpose a blacklist can be calculated on each node so that the leadership is not passed on. The number of nodes in the blacklist is minimum 0, maximum number of all nodes minus one. Each node calculates about all its fellow nodes. That is, we have conditionally 7 nodes and 7 nodes will calculate this thing. If it is different for all of them, it is at least some yellow level, we should contact the developers. This thing should be the same for everyone.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "consensus_bft_blacklist_count{instance=~\"$instance\",channel=~\"$channel\"}",
       "legendFormat": "{{ instance }}"
      }
     ]
    },
    {
     "title": "Node ID in blacklist",
     "type": "timeseries",
     "description": "Now it is not, but there is a possibility to set up a consensus, (now the leader, until he discredits himself, he processes everything, there is a vulnerability attack on the leader), to prevent this thing from happening you can say that this particular leader should calculate a certain number of solutions and pass the leadership on.For this purpose a blacklist can be calculated on each node so that the leadership is not passed on.The number of nodes in the blacklist is minimum 0, maximum number of all nodes minus one. Each node calculates about all its fellow nodes. That is, we have conditionally 7 nodes and 7 nodes will calculate this thing. If it is different for all of them, it is at least some yellow level, we should contact the developers. This thing should be the same for everyone.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "consensus_bft_node_id_in_blacklist{instance=~\"$instance\",channel=~\"$channel\"}",
       "legendFormat": "{{ instance }} blackid: {{ blackid }}"
      }
     ]
    }
   ]
  }
 ]
}