{
 "title": "Robot Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "robot_app_info" } }
  ]
 },
 "panels": [
  { "title": "General info", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "App Init Duration Seconds",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "robot_app_init_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{job}}"
    }
   ]
  },
  {
   "title": "App Info",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 4, "y": 1 },
   "targets": [
    {
     "expr": "robot_app_info{instance=~\"$instance\"}"
    }
   ]
  },
  {
   "title": "Height Ledger Blocks",
   "type": "stat",
   "description": " ledger's block num where batch was committed. Takes after every executeBatch",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "robot_height_ledger_blocks{instance=~\"$instance\"}",
     "legendFormat": "{{ robot }}"
    }
   ]
  },
  {
   "title": "Started",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "robot_started_total{instance=~\"$instance\"}",
     "legendFormat": "{{robot}}"
    }
   ]
  },
  {
   "title": "Stopped without errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(robot_stopped_total{instance=~\"$instance\",iserr=\"false\"}[$__rate_interval])) by (robot)",
     "legendFormat": "{{robot}}"
    }
   ]
  },
  {
   "title": "Stopped with errors",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(robot_stopped_total{instance=~\"$instance\",iserr=\"true\"}[$__rate_interval])) by (robot,errtype)",
     "legendFormat": "{{robot}} {{errtype}}"
    }
   ]
  },
  {
   "title": "Amount of executed transactions (in all executed batches) ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(robot_tx_executed_total{instance=~\"$instance\"}[$__rate_interval])) by (robot, txtype)",
     "legendFormat": "{{ robot }} {{ txtype }}"
    }
   ]
  },
  {
   "title": "Collector process block num",
   "type": "timeseries",
   "description": "the block number processing by the collector",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "expr": "sum(rate(robot_collector_process_block_num{instance=~\"$instance\"}[$__rate_interval])) by (channel)",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "Block Tx Count 95 percentille",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(robot_block_tx_count_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le, channel))",
     "legendFormat": "{{channel}}"
    }
   ]
  },
  {
   "title": "TX waiting process count",
   "type": "timeseries",
   "description": "amount of transactions (counts everything that is in a batch - transaction ids, swaps, multiswaps, keys of swaps and keys of multiswaps) awaiting execution when collector added them into a queue",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "targets": [
    {
     "expr": "robot_tx_waiting_process_count{instance=~\"$instance\"}",
     "legendFormat": "robot: {{ robot }}, channel: {{ channel }}"
    }
   ]
  },
  { "title": "Batches", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Batch size total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(rate(robot_batch_size_bytes_total{instance=~\"$instance\"}[$__rate_interval])) by (robot)",
     "legendFormat": "{{ robot }}"
    }
   ]
  },
  {
   "title": "Batches executed total",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(robot_batches_executed_total{instance=~\"$instance\",iserr=\"false\"}[$__rate_interval])) by (robot)",
     "legendFormat": "{{ robot }}"
    }
   ]
  },
  {
   "title": "Batches executed errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 27 },
   "targets": [
    {
     "expr": "sum(rate(robot_batches_executed_total{instance=~\"$instance\",iserr=\"true\"}[$__rate_interval])) by (robot)",
     "legendFormat": "{{ robot }}"
    }
   ]
  },
  {
   "title": "Batch Collect Duration Seconds 95 percentille",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(robot_batch_collect_duration_seconds_bucket{instance=~\"$instance\"}[$__rate_interval])) by (le, robot))",
     "legendFormat": "{{instance}} {{robot}}"
    }
   ]
  },
  {
   "title": "Batch execute duration seconds  95 percentille",
   "type": "timeseries",
   "description": "Batch collects by asking collectors. Batch is ready when one of the batch limits on the number of transactions, size or timeout occurs",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 35 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, robot_batch_execute_duration_seconds_bucket{instance=~\"$instance\"})",
     "legendFormat": "{{ robot }}"
    }
   ]
  },
  {
   "title": "Batch Size 95 percentille",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, robot_batch_size_bytes_bucket{instance=~\"$instance\"})",
     "legendFormat": "{{ robot }}"
    }
   ]
  },
  {
   "title": "Batch Size Estimated Diff 95 percentille",
   "type": "timeseries",
   "description": "Relative difference between real and assumed batch size",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, robot_batch_size_estimated_diff_bucket{instance=~\"$instance\"})",
     "legendFormat": "{{robot}}"
    }
   ]
  },
  {
   "title": "Batch TX count 95 percentille",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, robot_batch_tx_count_bucket{instance=~\"$instance\"})",
     "legendFormat": "{{ robot }}"
    }
   ]
  },
  {
   "title": "Amount of times request size was exceeded during executeBatch",
   "type": "timeseries",
   "description": "Labels:\nrobot - robot's destination channel\nis_first_attempt - whether it is a first attempt or not - true, false ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "sum(rate(robot_ord_reqsize_exceeded_total{instance=~\"$instance\"}[$__rate_interval])) by (robot, is_first_attempt)",
     "legendFormat": "{{ robot }} is_first_attempt={{ is_first_attempt }}"
    }
   ]
  },
  {
   "title": "Amount of times there was an error on creating HLF events source",
   "type": "timeseries",
   "description": "Labels:\nrobot - robot's destination channel\nchannel - robot's source channel\nis_first_attempt - whether it is a first attempt or not - true, false\nis_src_ch_closed - whether source channel was closed or not - true, false\nis_timeout - whether await timeout was reached - true, false",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 51 },
   "targets": [
    {
     "expr": "sum(rate(robot_src_channel_errors_total{instance=~\"$instance\"}[$__rate_interval])) by (robot, channel, is_first_attempt, is_src_ch_closed, is_timeout )",
     "legendFormat": "robot={{ robot}} channel={{ channel}} {{ is_first_attempt}} {{ is_src_ch_closed}} {{ is_timeout }}"
    }
   ]
  }
 ]
}